name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository at the push commit
      - uses: actions/checkout@v2

      # Minify step
      - name: Minify Action
        uses: anthonyftwang/minify-action@v1.0.1

      # Auto-commit the changes to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Minify source code
          branch: ${{ github.ref }}
